# Pandas - Introduction

Hi, my name's Adrian. In this opportunity, I'm starting to build my own portfolio about data analysis. My career goal is to become a data analyst applied to business intelligence. And I want to improrve my python skills applied in the use of pandas library. This notebook is like a little introduction of my way of mind and work. I hope you like it.

## How install the pandas library
You have to open your console. First, press to "Win" + "R" and write <code>"cmd"</code>. Using this combination, you can access to the windows console. Once time into, write the below code:  
<code>pip install pandas</code>

## Importación de librería

In [161]:
import pandas as pd

## Importación de Data

### Nuevos nombres de columnas
I like my data to be complete and consistent, so I'll rename the columns to have a clearer picture of what we see actually.

In [162]:
Col_Names = ['IDInvoice', 'Branch', 'City', 'Customer Type', 'Gender', 'Product Line', 'Unit Price', 'Quantity', 'Tax 5 Percentage', 'Total', 'Date', 'Hour', 'Payment Type', 'COGS', 'Gross Margin Percentage', 'Gross Income', 'Rating']

### Data
Use the method <code>read_csv</code> to import our data in a csv file. This data is about the some supermarket's sales in a some period of time specific.

In [163]:
Sales_CSV = pd.read_csv(filepath_or_buffer="../Supermarket - Sales.csv", sep=",", names=Col_Names, index_col='IDInvoice', header=0, quotechar='"')
Sales_CSV

,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5 Percentage,Total,Date,Hour,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating
IDInvoice,,,,,,,,,,,,,,,,
750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

## Exercises

### Show the 3 first rows the data.

In [164]:
Sales_CSV.head(3)

,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5 Percentage,Total,Date,Hour,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating
IDInvoice,,,,,,,,,,,,,,,,
750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4

### Show the 3 last rows the data.

In [165]:
Sales_CSV.tail(3)

,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5 Percentage,Total,Date,Hour,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating
IDInvoice,,,,,,,,,,,,,,,,
727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.592,33.432,2/9/2019,13:22,Cash,31.84,4.761905,1.592,7.7
347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.291,69.111,2/22/2019,15:33,Cash,65.82,4.761905,3.291,4.1
849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.919,649.299,2/18/2019,13:28,Cash,618.38,4.761905,30.919,6.6

### What the shape of our data?

In [166]:
Sales_CSV.shape ## (# Number of rows, # Number of columns)
print(Sales_CSV.shape)
print('Number of rows: ', Sales_CSV.shape[0])
print('Number of columns: ', Sales_CSV.shape[1])

(1000, 16)
Number of rows:  1000
Number of columns:  16

### Know the structure of our data

In [167]:
Sales_CSV.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 750-67-8428 to 849-09-3807
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Branch                   1000 non-null   object
 1   City                     1000 non-null   object
 2   Customer Type            1000 non-null   object
 3   Gender                   1000 non-null   object
 4   Product Line             1000 non-null   object
 5   Unit Price               1000 non-null   float64
 6   Quantity                 1000 non-null   int64
 7   Tax 5 Percentage         1000 non-null   float64
 8   Total                    1000 non-null   float64
 9   Date                     1000 non-null   object
 10  Hour                     1000 non-null   object
 11  Payment Type             1000 non-null   object
 12  COGS                     1000 non-null   float64
 13  Gross Margin Percentage  1000 non-null   float64
 14  Gross Income             1000 non-null   float64
 15  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(8)
memory usage: 132.8+ KB

### Check if your data has null values.

In [168]:
## Null values in all dataset
Sales_CSV.isnull()

,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5 Percentage,Total,Date,Hour,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating
IDInvoice,,,,,,,,,,,,,,,,
750-67-8428,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
226-31-3081,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
631-41-3108,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
123-19-1176,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
373-73-7910,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233-67-5758,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
303-96-2227,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
727-02-1313,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
347-56-2442,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
849-09-3807,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [169]:
## Null values by columns
Sales_CSV.isnull().sum() 
Sales_CSV.isnull().sum(axis=0) ### Default

Branch                     0
City                       0
Customer Type              0
Gender                     0
Product Line               0
Unit Price                 0
Quantity                   0
Tax 5 Percentage           0
Total                      0
Date                       0
Hour                       0
Payment Type               0
COGS                       0
Gross Margin Percentage    0
Gross Income               0
Rating                     0
dtype: int64

In [170]:
## Null values by rows
Sales_CSV.isnull().sum(axis=1)

IDInvoice
750-67-8428    0
226-31-3081    0
631-41-3108    0
123-19-1176    0
373-73-7910    0
              ..
233-67-5758    0
303-96-2227    0
727-02-1313    0
347-56-2442    0
849-09-3807    0
Length: 1000, dtype: int64

### Get overall statistic about the dataframe (only numeric values).

In [171]:
## If you want get overall statistics of all columns, you can ...
Sales_CSV.describe(include='all')
## In default context, only show us the statitstic for numeric data
Sales_CSV.describe()

,Unit Price,Quantity,Tax 5 Percentage,Total,COGS,Gross Margin Percentage,Gross Income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,0.000000,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905,49.650000,10.00000

### Find unique values from the gender columns

In [172]:
Genders = pd.DataFrame(data=Sales_CSV['Gender'].unique(), columns={'Gender':0})
Genders

   Gender
0  Female
1    Male

### Find the number of unique values from the gender columns. (Not frequency).

In [173]:
Sales_CSV['Gender'].nunique()

2

### Display count of unique values in gender columnn. (Frequency).

In [174]:
Sales_CSV['Gender'].value_counts()

Female    501
Male      499
Name: Gender, dtype: int64

### Filtering our data

In [175]:
# Find specific values
Sales_CSV[Sales_CSV['Payment Type'] == 'Cash']
# Using the logical operator "&"
Sales_CSV[(Sales_CSV['Rating'] >= 3) & (Sales_CSV['Rating'] <= 7)]
# Using the logical operator "|"
Sales_CSV[(Sales_CSV['Branch'] == 'A') | (Sales_CSV['Branch'] == 'C')]

,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5 Percentage,Total,Date,Hour,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating
IDInvoice,,,,,,,,,,,,,,,,
750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
652-49-6720,C,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,63.9975,2/18/2019,11:40,Ewallet,60.95,4.761905,3.0475,5.9
233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

#### Know the number of records of the filtered data.

In [176]:
print(len(Sales_CSV[Sales_CSV['Payment Type'] == 'Cash']))
print(len(Sales_CSV[(Sales_CSV['Rating'] >= 3) & (Sales_CSV['Rating'] <= 7)]))
print(len(Sales_CSV[(Sales_CSV['Branch'] == 'A') | (Sales_CSV['Branch'] == 'C')]))

344
519
668

#### Know the number of records of the filtered data (using the method "between")

In [177]:
sum(Sales_CSV['Rating'].between(3, 7))

519

### Find the value of the average rating.

In [178]:

Sales_CSV['Rating'].mean()

6.9727

### Using functions
Create a function that divide the value of the data by 2

In [179]:
def marks(x):
    return x/2

Using our created function and appling to our data

In [180]:
Sales_CSV['Unit Price'].apply(marks)

IDInvoice
750-67-8428    37.345
226-31-3081     7.640
631-41-3108    23.165
123-19-1176    29.110
373-73-7910    43.155
                ...
233-67-5758    20.175
303-96-2227    48.690
727-02-1313    15.920
347-56-2442    32.910
849-09-3807    44.170
Name: Unit Price, Length: 1000, dtype: float64

Also, we able to add a new column applying some function created by us.

In [181]:
Sales_CSV['Half Unit Price'] = Sales_CSV['Unit Price'].apply(marks)
Sales_CSV

,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5 Percentage,Total,Date,Hour,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating,Half Unit Price
IDInvoice,,,,,,,,,,,,,,,,,
750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,37.345
226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,7.640
631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,23.165
123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,29.110
373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,43.155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2,20.175
303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4,48.690
727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7,15.920
347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1,32.910
849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6,44.170

Or, we can use <code>"lambda"</code> for apply some function to each element of a specific column and to get a new values.

In [182]:
Sales_CSV['Unit Price'].apply(lambda x: x/2)

IDInvoice
750-67-8428    37.345
226-31-3081     7.640
631-41-3108    23.165
123-19-1176    29.110
373-73-7910    43.155
                ...
233-67-5758    20.175
303-96-2227    48.690
727-02-1313    15.920
347-56-2442    32.910
849-09-3807    44.170
Name: Unit Price, Length: 1000, dtype: float64

Or, we can use <code>"apply"</code> to apply built-in function to our dataset.

In [183]:
Sales_CSV['City'].apply(len)

IDInvoice
750-67-8428    6
226-31-3081    9
631-41-3108    6
123-19-1176    6
373-73-7910    6
              ..
233-67-5758    9
303-96-2227    8
727-02-1313    6
347-56-2442    6
849-09-3807    6
Name: City, Length: 1000, dtype: int64

### Assign general new values to represent repeated values in a same column.

In [184]:
Sales_CSV['Gender'].map({'Male':1, 'Female':0})

IDInvoice
750-67-8428    0
226-31-3081    0
631-41-3108    1
123-19-1176    1
373-73-7910    1
              ..
233-67-5758    1
303-96-2227    0
727-02-1313    1
347-56-2442    1
849-09-3807    0
Name: Gender, Length: 1000, dtype: int64

Add this new representation of values as a new column in our dataset.

In [185]:
Sales_CSV['Male_Female'] = Sales_CSV['Gender'].map({'Male':1, 'Female':0})
Sales_CSV

,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5 Percentage,Total,Date,Hour,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating,Half Unit Price,Male_Female
IDInvoice,,,,,,,,,,,,,,,,,,
750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,37.345,0
226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,7.640,0
631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,23.165,1
123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,29.110,1
373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,43.155,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2,20.175,1
303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4,48.690,0
727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7,15.920,1
347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1,32.910,1
849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6,44.170,0

### Delete column(s)
With the <code>"inplace"</code> argument, not necessary assign again to the DataFrame main variable.

In [186]:
Sales_CSV.drop(['Half Unit Price', 'Male_Female'], axis=1, inplace=True)
Sales_CSV

,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5 Percentage,Total,Date,Hour,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating
IDInvoice,,,,,,,,,,,,,,,,
750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

By default: If not use the "inplace" argument, then assign againt to the DataFrame variable.

In [ ]:
Sales_CSV = Sales_CSV.drop(['Half Unit Price', 'Male_Female'], axis=1, inplace=False)
Sales_CSV

### Know the name columns

In [189]:
Sales_CSV.columns

Index(['Branch', 'City', 'Customer Type', 'Gender', 'Product Line',
       'Unit Price', 'Quantity', 'Tax 5 Percentage', 'Total', 'Date', 'Hour',
       'Payment Type', 'COGS', 'Gross Margin Percentage', 'Gross Income',
       'Rating'],
      dtype='object')

### Know the index of our dataset.

In [190]:
Sales_CSV.index

Index(['750-67-8428', '226-31-3081', '631-41-3108', '123-19-1176',
       '373-73-7910', '699-14-3026', '355-53-5943', '315-22-5665',
       '665-32-9167', '692-92-5582',
       ...
       '886-18-2897', '602-16-6955', '745-74-0715', '690-01-6631',
       '652-49-6720', '233-67-5758', '303-96-2227', '727-02-1313',
       '347-56-2442', '849-09-3807'],
      dtype='object', name='IDInvoice', length=1000)

### Ordering our DataFrame.

In [191]:
Sales_CSV.sort_values(by='Date', ascending=True)
Sales_CSV.sort_values(by=['Date', 'Hour'], ascending=True)
Sales_CSV.sort_values(by=['Date', 'Hour'], ascending=False)

,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5 Percentage,Total,Date,Hour,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating
IDInvoice,,,,,,,,,,,,,,,,
815-11-1168,A,Yangon,Member,Male,Food and beverages,99.78,5,24.945,523.845,3/9/2019,19:09,Cash,498.90,4.761905,24.945,5.4
157-13-5295,A,Yangon,Member,Male,Health and beauty,51.94,10,25.970,545.370,3/9/2019,18:24,Ewallet,519.40,4.761905,25.970,6.5
841-35-6630,C,Naypyitaw,Normal,Female,Electronic accessories,75.91,6,22.773,478.233,3/9/2019,18:21,Cash,455.46,4.761905,22.773,8.7
132-32-9879,B,Mandalay,Member,Female,Electronic accessories,93.96,4,18.792,394.632,3/9/2019,18:00,Cash,375.84,4.761905,18.792,9.5
219-22-9386,B,Mandalay,Member,Male,Sports and travel,99.96,9,44.982,944.622,3/9/2019,17:26,Credit card,899.64,4.761905,44.982,4.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
651-88-7328,A,Yangon,Normal,Female,Fashion accessories,65.74,9,29.583,621.243,1/1/2019,13:55,Cash,591.66,4.761905,29.583,7.7
133-14-7229,C,Naypyitaw,Normal,Male,Health and beauty,62.87,2,6.287,132.027,1/1/2019,11:43,Cash,125.74,4.761905,6.287,5.0
271-77-8740,C,Naypyitaw,Member,Female,Sports and travel,29.22,6,8.766,184.086,1/1/2019,11:40,Ewallet,175.32,4.761905,8.766,5.0
746-04-1077,B,Mandalay,Member,Female,Food and beverages,84.63,10,42.315,888.615,1/1/2019,11:36,Credit card,846.30,4.761905,42.315,9.0
765-26-6951,A,Yangon,Normal,Male,Sports and travel,72.61,6,21.783,457.443,1/1/2019,10:39,Credit card,435.66,4.761905,21.783,6.9

### Filtering and sorting our data set at the same time.

In [192]:
Sales_CSV[Sales_CSV['Gender'] == 'Female'][['Date', 'Hour', 'Rating']].sort_values(['Date', 'Hour', 'Rating'])

                 Date   Hour  Rating
IDInvoice
746-04-1077  1/1/2019  11:36     9.0
271-77-8740  1/1/2019  11:40     5.0
651-88-7328  1/1/2019  13:55     7.7
416-17-9926  1/1/2019  14:42     4.3
556-97-7101  1/1/2019  15:51     8.5
...               ...    ...     ...
308-47-4913  3/9/2019  12:45     6.2
652-43-6591  3/9/2019  13:18     6.2
268-27-6179  3/9/2019  14:57     7.3
132-32-9879  3/9/2019  18:00     9.5
841-35-6630  3/9/2019  18:21     8.7

[501 rows x 3 columns]